-- CREATE DATABASE IF NOT EXISTS nutri_esportiva;
-- USE nutri_esportiva;

-- CREATE TABLE Usuario (
--     id_usuario   INT PRIMARY KEY AUTO_INCREMENT,
--     nome  VARCHAR(100) NOT NULL,
--     email VARCHAR(100) NOT NULL UNIQUE,
--     senha   VARCHAR(255) NOT NULL,
--     data_nascimento DATE NOT NULL,
--     telefone VARCHAR(20) NOT NULL,
--     registro VARCHAR(50),
--     tipo_perfil ENUM('Atleta', 'Nutricionista', 'Treinador', 'Medico', 'Suporte', 'Admin') NOT NULL,
--     situacao ENUM ('Pendente', 'Ativo', 'Desativado') DEFAULT ('Pendente') NOT NULL
-- );

-- CREATE TABLE Atleta_Perfil (
--     id_atleta            INT          PRIMARY KEY,
--     idade                INT,
--     sexo                 ENUM('M', 'F'),
--     altura               DECIMAL(3,2),
--     peso                 DECIMAL(5,2),
--     modalidade_esportiva VARCHAR(50),
--     id_nutricionista     INT,
--     id_treinador         INT,
--     FOREIGN KEY (id_atleta)        REFERENCES Usuario(id_usuario),
--     FOREIGN KEY (id_nutricionista) REFERENCES Usuario(id_usuario),
--     FOREIGN KEY (id_treinador)     REFERENCES Usuario(id_usuario)
-- );

-- CREATE TABLE Sessao_Treino (
--     id_sessao        INT           PRIMARY KEY AUTO_INCREMENT,
--     id_atleta        INT           NOT NULL,
--     data_hora_inicio TIMESTAMP     NOT NULL,
--     duracao_minutos  INT,
--     massa_pre        DECIMAL(5,2),
--     massa_pos        DECIMAL(5,2),
--     volume_urina_ml  DECIMAL(6,2),
--     lat              DECIMAL(10,8),
--     lon              DECIMAL(11,8),
--     clima_temp       DECIMAL(4,1),
--     clima_umidade    INT,
--     clima_sensacao   DECIMAL(4,1),
--     clima_vento      DECIMAL(5,2),
--     status_sessao    ENUM('Pendente', 'Concluída') NOT NULL DEFAULT 'Pendente',
--     intensidade_percebida ENUM('Baixa','Média','Alta'),
--     roupas_encharcadas TINYINT(1) DEFAULT 0,
--     urina_pre_cor TINYINT,
--     FOREIGN KEY (id_atleta) REFERENCES Atleta_Perfil(id_atleta)
-- );

-- CREATE TABLE Registro_Hidratacao (
--     id_registro      INT          PRIMARY KEY AUTO_INCREMENT,
--     id_sessao        INT          NOT NULL,
--     volume_ml        DECIMAL(6,2) NOT NULL,
--     timestamp_evento TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (id_sessao) REFERENCES Sessao_Treino(id_sessao)
-- );

-- CREATE TABLE Resultado_Calculo (
--     id_resultado         INT          PRIMARY KEY AUTO_INCREMENT,
--     id_sessao            INT          NOT NULL,
--     perda_massa_ajustada DECIMAL(5,2),
--     taxa_sudorese        DECIMAL(8,2),
--     percentual_variacao  DECIMAL(5,2),
--     recomendacao_texto   VARCHAR(255),
--     alerta_seguranca     TEXT,
--     status_color         ENUM('Verde', 'Amarelo', 'Vermelho'),
--     FOREIGN KEY (id_sessao) REFERENCES Sessao_Treino(id_sessao)
-- );

-- CREATE TABLE Saude_Sintomas (
--     id_saude                   INT  PRIMARY KEY AUTO_INCREMENT,
--     id_sessao                  INT  NOT NULL,
--     nivel_fadiga               INT,
--     sintomas_gastrointestinais TEXT,
--     FOREIGN KEY (id_sessao) REFERENCES Sessao_Treino(id_sessao)
-- );

-- CREATE TABLE Logs_Auditoria (
--     id_log     INT          PRIMARY KEY AUTO_INCREMENT,
--     id_usuario INT          NOT NULL,
--     acao       VARCHAR(255) NOT NULL,
--     data_hora  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (id_usuario) REFERENCES Usuario(id_usuario)
-- );

-- INSERT INTO Usuario (nome, email, senha, data_nascimento, telefone, registro, tipo_perfil, situacao) VALUES
-- ('Jose',      'Adm@teste.com',       '$2b$10$qEFnKj..ohns..q7gUhkueY3Vn0ziRoB/YFKWyRJIZ0MbfDtHK8qK', '1985-03-12', '11987650001', null,  'Admin', 'Ativo'),
-- ('Rodrigo',   'atleta@teste.com',    '$2b$10$qEFnKj..ohns..q7gUhkueY3Vn0ziRoB/YFKWyRJIZ0MbfDtHK8qK', '1998-07-25', '11987650002', 'REG-0002', 'Atleta', 'Ativo'),
-- ('Marcia',    'medico@teste.com',    '$2b$10$qEFnKj..ohns..q7gUhkueY3Vn0ziRoB/YFKWyRJIZ0MbfDtHK8qK', '1980-11-03', '11987650003', 'CRM-12345', 'Medico', 'Ativo'),
-- ('Pedro',     'nutri@teste.com',     '$2b$10$qEFnKj..ohns..q7gUhkueY3Vn0ziRoB/YFKWyRJIZ0MbfDtHK8qK', '1990-01-18', '11987650004', 'CRN-67890', 'Nutricionista', 'Ativo'),
-- ('Guilherme', 'treinador@teste.com', '$2b$10$qEFnKj..ohns..q7gUhkueY3Vn0ziRoB/YFKWyRJIZ0MbfDtHK8qK', '1992-09-30', '11987650005', null , 'Treinador', 'Ativo');

